apiVersion: v1
data:
  prismCentral: |-
    {
      "address": "{{ .Values.vmoperator.pc }}",
      "port": 9440,
      "insecure": true,
      "credentialRef": {
        "kind": "secret",
        "name": "nutanix-creds"
      },
      "additionalTrustBundle": {
        "kind": "ConfigMap",
        "name": "nutanix-trustbundle"
      }
    }
kind: ConfigMap
metadata:
  name: nutanix-endpoint
  namespace: vm-operator-system
---
apiVersion: v1
binaryData:
  ca.crt: ""
kind: ConfigMap
metadata:
  name: nutanix-trustbundle
  namespace: vm-operator-system

