apiVersion: v1
data:
  prismCentral: |-
    {
      "address": "{{ .Values.vm-operator.pc }}",
      "port": 9440,
      "insecure": true,
      "credentialRef": {
        "kind": "secret",
        "name": "nutanix-creds"
      },
      "additionalTrustBundle": {
        "kind": "ConfigMap",
        "name": "nutanix-trustbundle"
      }
    }
kind: ConfigMap
metadata:
  name: nutanix-endpoint
  namespace: vm-operator-system
---
apiVersion: v1
binaryData:
  ca.crt: ""
kind: ConfigMap
metadata:
  name: nutanix-trustbundle
  namespace: vm-operator-system
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nutanix-creds
  namespace: vm-operator-system
stringData:
  credentials: |
    [
      {
        "type": "basic_auth", 
        "data": { 
          "prismCentral":{
            "username": "{{ .Values.vm-operator.username }}",
            "password": "{{ .Values.vm-operator.password }}"
          },
          "prismElements": null
        }
      }
    ]
