---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: nutanix-creds
  namespace: vm-operator-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: nutanix-creds
    template:
      type: Opaque
      metadata:
        name: nutanix-creds
        namespace: vm-operator-system
      data:
        credentials: |
          [
            {
              "type": "basic_auth", 
              "data": { 
                "prismCentral":{
                  "username": "{{ .data.user }}",
                  "password": "{{ .data.pass }}"
                },
                "prismElements": null
              }
            }
          ]
  dataFrom:
  - extract:
      key: {{ .Values.credentialsecret.key }}