
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-operator-controller-manager
  namespace: vm-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-operator-leader-election-role
  namespace: vm-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: vm-operator-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutaniximages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutaniximages/finalizers
  verbs:
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutaniximages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachineimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachineimports/finalizers
  verbs:
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachineimports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachineservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachineservices/finalizers
  verbs:
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachineservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachinesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachinesets/finalizers
  verbs:
  - update
- apiGroups:
  - vm.nutanix.com
  resources:
  - nutanixvirtualmachinesets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-operator-leader-election-rolebinding
  namespace: vm-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: vm-operator-controller-manager
  namespace: vm-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vm-operator-manager-role
subjects:
- kind: ServiceAccount
  name: vm-operator-controller-manager
  namespace: vm-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vm-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: vm-operator-controller-manager
  namespace: vm-operator-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: eef3c0c0.nutanix.com
    # leaderElectionReleaseOnCancel defines if the leader should step down volume
    # when the Manager ends. This requires the binary to immediately end when the
    # Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
    # speeds up voluntary leader transitions as the new leader don't have to wait
    # LeaseDuration time first.
    # In the default scaffold provided, the program ends immediately after
    # the manager stops, so would be fine to enable this option. However,
    # if you are doing or is intended to do any operation such as perform cleanups
    # after the manager stops then its usage might be unsafe.
    # leaderElectionReleaseOnCancel: true
kind: ConfigMap
metadata:
  name: vm-operator-manager-config
  namespace: vm-operator-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: vm-operator-controller-manager-metrics-service
  namespace: vm-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: vm-operator-webhook-service
  namespace: vm-operator-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vm-operator
    control-plane: controller-manager
  name: vm-operator-controller-manager
  namespace: vm-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: vm-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/nutanix-cloud-native/vm-operator/controller:dev-35b5471
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /etc/nutanix/config
          name: endpoint
        - mountPath: /etc/ssl/certs
          name: cacerts
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: vm-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      - configMap:
          name: nutanix-endpoint
        name: endpoint
      - configMap:
          name: nutanix-trustbundle
        name: cacerts
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vm-operator-serving-cert
  namespace: vm-operator-system
spec:
  dnsNames:
  - vm-operator-webhook-service.vm-operator-system.svc
  - vm-operator-webhook-service.vm-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: vm-operator-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vm-operator-selfsigned-issuer
  namespace: vm-operator-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: vm-operator-system/vm-operator-serving-cert
  name: vm-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vm-operator-webhook-service
      namespace: vm-operator-system
      path: /mutate-vm-nutanix-com-v1alpha1-nutanixvirtualmachine
  failurePolicy: Fail
  name: mnutanixvirtualmachine.kb.io
  rules:
  - apiGroups:
    - vm.nutanix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nutanixvirtualmachines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: vm-operator-system/vm-operator-serving-cert
  name: vm-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vm-operator-webhook-service
      namespace: vm-operator-system
      path: /validate-vm-nutanix-com-v1alpha1-nutanixvirtualmachine
  failurePolicy: Fail
  name: vnutanixvirtualmachine.kb.io
  rules:
  - apiGroups:
    - vm.nutanix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nutanixvirtualmachines
  sideEffects: None
